include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(PID_SIMULATOR_SOURCE_DIRECTORY
    ${PID_SIMULATOR_DIR}/src
)

set(PID_SIMULATOR_TEST_DIRECTORY
    ${PID_SIMULATOR_DIR}/tst
)

set(PID_SIMULATOR_MAIN_DIRECTORY
    ${PID_SIMULATOR_DIR}/main
)

set(PID_SIMULATOR_INCLUDE_DIRECTORIES
    ${PID_SIMULATOR_SOURCE_DIRECTORY}
)

set(PID_SIMULATOR_TEST_INCLUDE_DIRECTORIES
    ${PID_SIMULATOR_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${PID_SIMULATOR_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(PID_SIMULATOR_SOURCE_DIRECTORY_LIST ${PID_SIMULATOR_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(PID_SIMULATOR_SOURCES PID_SIMULATOR_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${PID_SIMULATOR_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(PID_SIMULATOR_TEST_DIRECTORY_LIST ${PID_SIMULATOR_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(PID_SIMULATOR_TESTS PID_SIMULATOR_TEST_DIRECTORY_LIST)

PRINT_STATUS("Looking for MAIN directories in: [${PID_SIMULATOR_MAIN_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(PID_SIMULATOR_MAIN_DIRECTORY_LIST ${PID_SIMULATOR_MAIN_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(PID_SIMULATOR_MAIN_SOURCES PID_SIMULATOR_MAIN_DIRECTORY_LIST)

set(PID_SIMULATOR_SOURCES_AND_TESTS
    ${PID_SIMULATOR_SOURCES}
    ${PID_SIMULATOR_TESTS}
)
