include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY
    ${LRM_ALLOCATION_SIMULATOR_DIR}/src
)

set(LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY
    ${LRM_ALLOCATION_SIMULATOR_DIR}/tst
)

set(LRM_ALLOCATION_SIMULATOR_MAIN_DIRECTORY
    ${LRM_ALLOCATION_SIMULATOR_DIR}/main
)

set(LRM_ALLOCATION_SIMULATOR_INCLUDE_DIRECTORIES
    ${LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY}
)

set(LRM_ALLOCATION_SIMULATOR_TEST_INCLUDE_DIRECTORIES
    ${LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY_LIST ${LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(LRM_ALLOCATION_SIMULATOR_SOURCES LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY_LIST ${LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(LRM_ALLOCATION_SIMULATOR_TESTS LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY_LIST)

PRINT_STATUS("Looking for MAIN directories in: [${LRM_ALLOCATION_SIMULATOR_MAIN_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(LRM_ALLOCATION_SIMULATOR_MAIN_DIRECTORY_LIST ${LRM_ALLOCATION_SIMULATOR_MAIN_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(LRM_ALLOCATION_SIMULATOR_MAIN_SOURCES LRM_ALLOCATION_SIMULATOR_MAIN_DIRECTORY_LIST)

set(LRM_ALLOCATION_SIMULATOR_SOURCES_AND_TESTS
    ${LRM_ALLOCATION_SIMULATOR_SOURCES}
    ${LRM_ALLOCATION_SIMULATOR_TESTS}
)
