#Include zlib, this needs APRG Directory
include(${APRG_DIR}/zlib128/AprgCmakeInclude/zlib.cmake)

#Assign curl directory, this needs aprg directory
set(CURL_DIR ${APRG_DIR}/curl-7.38.0/curl-7.38.0/)

#Include curl library
set(CURL_INCLUDE_DIRECTORIES
    ${CURL_DIR}/include
    ${CURL_DIR}
    ${CURL_DIR}/src
)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCURL_STATICLIB -DHAVE_ZLIB_H -DHAVE_LIBZ")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DCURL_STATICLIB -DHAVE_ZLIB_H -DHAVE_LIBZ")

set(CURL_LIB_SOURCES
    ${CURL_DIR}/include/curl/curl.h
    ${CURL_DIR}/include/curl/curlbuild.h
    ${CURL_DIR}/include/curl/curlrules.h
    ${CURL_DIR}/include/curl/curlver.h
    ${CURL_DIR}/include/curl/easy.h
    ${CURL_DIR}/include/curl/mprintf.h
    ${CURL_DIR}/include/curl/multi.h
    ${CURL_DIR}/include/curl/stdcheaders.h
    ${CURL_DIR}/include/curl/typecheck-gcc.h
    ${CURL_DIR}/lib/amigaos.c
    ${CURL_DIR}/lib/amigaos.h
    ${CURL_DIR}/lib/arpa_telnet.h
    ${CURL_DIR}/lib/asyn-ares.c
    ${CURL_DIR}/lib/asyn-thread.c
    ${CURL_DIR}/lib/asyn.h
    ${CURL_DIR}/lib/base64.c
    ${CURL_DIR}/lib/bundles.c
    ${CURL_DIR}/lib/bundles.h
    ${CURL_DIR}/lib/config-amigaos.h
    ${CURL_DIR}/lib/config-dos.h
    ${CURL_DIR}/lib/config-mac.h
    ${CURL_DIR}/lib/config-os400.h
    ${CURL_DIR}/lib/config-symbian.h
    ${CURL_DIR}/lib/config-tpf.h
    ${CURL_DIR}/lib/config-vxworks.h
    ${CURL_DIR}/lib/config-win32.h
    ${CURL_DIR}/lib/config-win32ce.h
    ${CURL_DIR}/lib/conncache.c
    ${CURL_DIR}/lib/conncache.h
    ${CURL_DIR}/lib/connect.c
    ${CURL_DIR}/lib/connect.h
    ${CURL_DIR}/lib/content_encoding.c
    ${CURL_DIR}/lib/content_encoding.h
    ${CURL_DIR}/lib/cookie.c
    ${CURL_DIR}/lib/cookie.h
    ${CURL_DIR}/lib/curlx.h
    ${CURL_DIR}/lib/curl_addrinfo.c
    ${CURL_DIR}/lib/curl_addrinfo.h
    ${CURL_DIR}/lib/curl_base64.h
    ${CURL_DIR}/lib/curl_fnmatch.c
    ${CURL_DIR}/lib/curl_fnmatch.h
    ${CURL_DIR}/lib/curl_gethostname.c
    ${CURL_DIR}/lib/curl_gethostname.h
    ${CURL_DIR}/lib/curl_gssapi.c
    ${CURL_DIR}/lib/curl_gssapi.h
    ${CURL_DIR}/lib/curl_hmac.h
    ${CURL_DIR}/lib/curl_ldap.h
    ${CURL_DIR}/lib/curl_md4.h
    ${CURL_DIR}/lib/curl_md5.h
    ${CURL_DIR}/lib/curl_memory.h
    ${CURL_DIR}/lib/curl_memrchr.c
    ${CURL_DIR}/lib/curl_memrchr.h
    ${CURL_DIR}/lib/curl_multibyte.c
    ${CURL_DIR}/lib/curl_multibyte.h
    ${CURL_DIR}/lib/curl_ntlm.c
    ${CURL_DIR}/lib/curl_ntlm.h
    ${CURL_DIR}/lib/curl_ntlm_core.c
    ${CURL_DIR}/lib/curl_ntlm_core.h
    ${CURL_DIR}/lib/curl_ntlm_msgs.c
    ${CURL_DIR}/lib/curl_ntlm_msgs.h
    ${CURL_DIR}/lib/curl_ntlm_wb.c
    ${CURL_DIR}/lib/curl_ntlm_wb.h
    ${CURL_DIR}/lib/curl_rtmp.c
    ${CURL_DIR}/lib/curl_rtmp.h
    ${CURL_DIR}/lib/curl_sasl.c
    ${CURL_DIR}/lib/curl_sasl.h
    ${CURL_DIR}/lib/curl_sasl_sspi.c
    ${CURL_DIR}/lib/curl_sec.h
    ${CURL_DIR}/lib/curl_setup.h
    ${CURL_DIR}/lib/curl_setup_once.h
    ${CURL_DIR}/lib/curl_sspi.c
    ${CURL_DIR}/lib/curl_sspi.h
    ${CURL_DIR}/lib/curl_threads.c
    ${CURL_DIR}/lib/curl_threads.h
    ${CURL_DIR}/lib/dict.c
    ${CURL_DIR}/lib/dict.h
    ${CURL_DIR}/lib/dotdot.c
    ${CURL_DIR}/lib/dotdot.h
    ${CURL_DIR}/lib/easy.c
    ${CURL_DIR}/lib/easyif.h
    ${CURL_DIR}/lib/escape.c
    ${CURL_DIR}/lib/escape.h
    ${CURL_DIR}/lib/file.c
    ${CURL_DIR}/lib/file.h
    ${CURL_DIR}/lib/fileinfo.c
    ${CURL_DIR}/lib/fileinfo.h
    ${CURL_DIR}/lib/formdata.c
    ${CURL_DIR}/lib/formdata.h
    ${CURL_DIR}/lib/ftp.c
    ${CURL_DIR}/lib/ftp.h
    ${CURL_DIR}/lib/ftplistparser.c
    ${CURL_DIR}/lib/ftplistparser.h
    ${CURL_DIR}/lib/getenv.c
    ${CURL_DIR}/lib/getinfo.c
    ${CURL_DIR}/lib/getinfo.h
    ${CURL_DIR}/lib/gopher.c
    ${CURL_DIR}/lib/gopher.h
    ${CURL_DIR}/lib/hash.c
    ${CURL_DIR}/lib/hash.h
    ${CURL_DIR}/lib/hmac.c
    ${CURL_DIR}/lib/hostasyn.c
    ${CURL_DIR}/lib/hostcheck.c
    ${CURL_DIR}/lib/hostcheck.h
    ${CURL_DIR}/lib/hostip.c
    ${CURL_DIR}/lib/hostip.h
    ${CURL_DIR}/lib/hostip4.c
    ${CURL_DIR}/lib/hostip6.c
    ${CURL_DIR}/lib/hostsyn.c
    ${CURL_DIR}/lib/http.c
    ${CURL_DIR}/lib/http.h
    ${CURL_DIR}/lib/http2.c
    ${CURL_DIR}/lib/http2.h
    ${CURL_DIR}/lib/http_chunks.c
    ${CURL_DIR}/lib/http_chunks.h
    ${CURL_DIR}/lib/http_digest.c
    ${CURL_DIR}/lib/http_digest.h
    ${CURL_DIR}/lib/http_negotiate.c
    ${CURL_DIR}/lib/http_negotiate.h
    ${CURL_DIR}/lib/http_negotiate_sspi.c
    ${CURL_DIR}/lib/http_proxy.c
    ${CURL_DIR}/lib/http_proxy.h
    ${CURL_DIR}/lib/idn_win32.c
    ${CURL_DIR}/lib/if2ip.c
    ${CURL_DIR}/lib/if2ip.h
    ${CURL_DIR}/lib/imap.c
    ${CURL_DIR}/lib/imap.h
    ${CURL_DIR}/lib/inet_ntop.c
    ${CURL_DIR}/lib/inet_ntop.h
    ${CURL_DIR}/lib/inet_pton.c
    ${CURL_DIR}/lib/inet_pton.h
    ${CURL_DIR}/lib/krb5.c
    ${CURL_DIR}/lib/ldap.c
    ${CURL_DIR}/lib/llist.c
    ${CURL_DIR}/lib/llist.h
    ${CURL_DIR}/lib/md4.c
    ${CURL_DIR}/lib/md5.c
    ${CURL_DIR}/lib/memdebug.c
    ${CURL_DIR}/lib/memdebug.h
    ${CURL_DIR}/lib/mprintf.c
    ${CURL_DIR}/lib/multi.c
    ${CURL_DIR}/lib/multihandle.h
    ${CURL_DIR}/lib/multiif.h
    ${CURL_DIR}/lib/netrc.c
    ${CURL_DIR}/lib/netrc.h
    ${CURL_DIR}/lib/non-ascii.c
    ${CURL_DIR}/lib/non-ascii.h
    ${CURL_DIR}/lib/nonblock.c
    ${CURL_DIR}/lib/nonblock.h
    ${CURL_DIR}/lib/nwlib.c
    ${CURL_DIR}/lib/nwos.c
    ${CURL_DIR}/lib/openldap.c
    ${CURL_DIR}/lib/parsedate.c
    ${CURL_DIR}/lib/parsedate.h
    ${CURL_DIR}/lib/pingpong.c
    ${CURL_DIR}/lib/pingpong.h
    ${CURL_DIR}/lib/pipeline.c
    ${CURL_DIR}/lib/pipeline.h
    ${CURL_DIR}/lib/pop3.c
    ${CURL_DIR}/lib/pop3.h
    ${CURL_DIR}/lib/progress.c
    ${CURL_DIR}/lib/progress.h
    ${CURL_DIR}/lib/rawstr.c
    ${CURL_DIR}/lib/rawstr.h
    ${CURL_DIR}/lib/rtsp.c
    ${CURL_DIR}/lib/rtsp.h
    ${CURL_DIR}/lib/security.c
    ${CURL_DIR}/lib/select.c
    ${CURL_DIR}/lib/select.h
    ${CURL_DIR}/lib/sendf.c
    ${CURL_DIR}/lib/sendf.h
    ${CURL_DIR}/lib/setup-os400.h
    ${CURL_DIR}/lib/setup-vms.h
    ${CURL_DIR}/lib/share.c
    ${CURL_DIR}/lib/share.h
    ${CURL_DIR}/lib/sigpipe.h
    ${CURL_DIR}/lib/slist.c
    ${CURL_DIR}/lib/slist.h
    ${CURL_DIR}/lib/smtp.c
    ${CURL_DIR}/lib/smtp.h
    ${CURL_DIR}/lib/sockaddr.h
    ${CURL_DIR}/lib/socks.c
    ${CURL_DIR}/lib/socks.h
    ${CURL_DIR}/lib/socks_gssapi.c
    ${CURL_DIR}/lib/socks_sspi.c
    ${CURL_DIR}/lib/speedcheck.c
    ${CURL_DIR}/lib/speedcheck.h
    ${CURL_DIR}/lib/splay.c
    ${CURL_DIR}/lib/splay.h
    ${CURL_DIR}/lib/ssh.c
    ${CURL_DIR}/lib/ssh.h
    ${CURL_DIR}/lib/strdup.c
    ${CURL_DIR}/lib/strdup.h
    ${CURL_DIR}/lib/strequal.c
    ${CURL_DIR}/lib/strequal.h
    ${CURL_DIR}/lib/strerror.c
    ${CURL_DIR}/lib/strerror.h
    ${CURL_DIR}/lib/strtok.c
    ${CURL_DIR}/lib/strtok.h
    ${CURL_DIR}/lib/strtoofft.c
    ${CURL_DIR}/lib/strtoofft.h
    ${CURL_DIR}/lib/telnet.c
    ${CURL_DIR}/lib/telnet.h
    ${CURL_DIR}/lib/tftp.c
    ${CURL_DIR}/lib/tftp.h
    ${CURL_DIR}/lib/timeval.c
    ${CURL_DIR}/lib/timeval.h
    ${CURL_DIR}/lib/transfer.c
    ${CURL_DIR}/lib/transfer.h
    ${CURL_DIR}/lib/url.c
    ${CURL_DIR}/lib/url.h
    ${CURL_DIR}/lib/urldata.h
    ${CURL_DIR}/lib/version.c
    ${CURL_DIR}/lib/vtls/axtls.c
    ${CURL_DIR}/lib/vtls/axtls.h
    ${CURL_DIR}/lib/vtls/curl_darwinssl.c
    ${CURL_DIR}/lib/vtls/curl_darwinssl.h
    ${CURL_DIR}/lib/vtls/curl_schannel.c
    ${CURL_DIR}/lib/vtls/curl_schannel.h
    ${CURL_DIR}/lib/vtls/cyassl.c
    ${CURL_DIR}/lib/vtls/cyassl.h
    ${CURL_DIR}/lib/vtls/gskit.c
    ${CURL_DIR}/lib/vtls/gskit.h
    ${CURL_DIR}/lib/vtls/gtls.c
    ${CURL_DIR}/lib/vtls/gtls.h
    ${CURL_DIR}/lib/vtls/nss.c
    ${CURL_DIR}/lib/vtls/nssg.h
    ${CURL_DIR}/lib/vtls/openssl.c
    ${CURL_DIR}/lib/vtls/openssl.h
    ${CURL_DIR}/lib/vtls/polarssl.c
    ${CURL_DIR}/lib/vtls/polarssl.h
    ${CURL_DIR}/lib/vtls/polarssl_threadlock.c
    ${CURL_DIR}/lib/vtls/polarssl_threadlock.h
    ${CURL_DIR}/lib/vtls/qssl.c
    ${CURL_DIR}/lib/vtls/qssl.h
    ${CURL_DIR}/lib/vtls/vtls.c
    ${CURL_DIR}/lib/vtls/vtls.h
    ${CURL_DIR}/lib/warnless.c
    ${CURL_DIR}/lib/warnless.h
    ${CURL_DIR}/lib/wildcard.c
    ${CURL_DIR}/lib/wildcard.h
    ${CURL_DIR}/lib/x509asn1.c
    ${CURL_DIR}/lib/x509asn1.h
    ${CURL_DIR}/src/tool_binmode.c
    ${CURL_DIR}/src/tool_binmode.h
    ${CURL_DIR}/src/tool_bname.c
    ${CURL_DIR}/src/tool_bname.h
    ${CURL_DIR}/src/tool_cb_dbg.c
    ${CURL_DIR}/src/tool_cb_dbg.h
    ${CURL_DIR}/src/tool_cb_hdr.c
    ${CURL_DIR}/src/tool_cb_hdr.h
    ${CURL_DIR}/src/tool_cb_prg.c
    ${CURL_DIR}/src/tool_cb_prg.h
    ${CURL_DIR}/src/tool_cb_rea.c
    ${CURL_DIR}/src/tool_cb_rea.h
    ${CURL_DIR}/src/tool_cb_see.c
    ${CURL_DIR}/src/tool_cb_see.h
    ${CURL_DIR}/src/tool_cb_wrt.c
    ${CURL_DIR}/src/tool_cb_wrt.h
    ${CURL_DIR}/src/tool_cfgable.c
    ${CURL_DIR}/src/tool_cfgable.h
    ${CURL_DIR}/src/tool_convert.c
    ${CURL_DIR}/src/tool_convert.h
    ${CURL_DIR}/src/tool_dirhie.c
    ${CURL_DIR}/src/tool_dirhie.h
    ${CURL_DIR}/src/tool_doswin.c
    ${CURL_DIR}/src/tool_doswin.h
    ${CURL_DIR}/src/tool_easysrc.c
    ${CURL_DIR}/src/tool_easysrc.h
    ${CURL_DIR}/src/tool_formparse.c
    ${CURL_DIR}/src/tool_formparse.h
    ${CURL_DIR}/src/tool_getparam.c
    ${CURL_DIR}/src/tool_getparam.h
    ${CURL_DIR}/src/tool_getpass.c
    ${CURL_DIR}/src/tool_getpass.h
    ${CURL_DIR}/src/tool_help.c
    ${CURL_DIR}/src/tool_help.h
    ${CURL_DIR}/src/tool_helpers.c
    ${CURL_DIR}/src/tool_helpers.h
    ${CURL_DIR}/src/tool_homedir.c
    ${CURL_DIR}/src/tool_homedir.h
    ${CURL_DIR}/src/tool_hugehelp.c
    ${CURL_DIR}/src/tool_hugehelp.h
    ${CURL_DIR}/src/tool_libinfo.c
    ${CURL_DIR}/src/tool_libinfo.h
    ${CURL_DIR}/src/tool_main.c
    ${CURL_DIR}/src/tool_main.h
    ${CURL_DIR}/src/tool_metalink.c
    ${CURL_DIR}/src/tool_metalink.h
    ${CURL_DIR}/src/tool_mfiles.c
    ${CURL_DIR}/src/tool_mfiles.h
    ${CURL_DIR}/src/tool_msgs.c
    ${CURL_DIR}/src/tool_msgs.h
    ${CURL_DIR}/src/tool_operate.c
    ${CURL_DIR}/src/tool_operate.h
    ${CURL_DIR}/src/tool_operhlp.c
    ${CURL_DIR}/src/tool_operhlp.h
    ${CURL_DIR}/src/tool_panykey.c
    ${CURL_DIR}/src/tool_panykey.h
    ${CURL_DIR}/src/tool_paramhlp.c
    ${CURL_DIR}/src/tool_paramhlp.h
    ${CURL_DIR}/src/tool_parsecfg.c
    ${CURL_DIR}/src/tool_parsecfg.h
    ${CURL_DIR}/src/tool_sdecls.h
    ${CURL_DIR}/src/tool_setopt.c
    ${CURL_DIR}/src/tool_setopt.h
    ${CURL_DIR}/src/tool_setup.h
    ${CURL_DIR}/src/tool_sleep.c
    ${CURL_DIR}/src/tool_sleep.h
    ${CURL_DIR}/src/tool_urlglob.c
    ${CURL_DIR}/src/tool_urlglob.h
    ${CURL_DIR}/src/tool_util.c
    ${CURL_DIR}/src/tool_util.h
    ${CURL_DIR}/src/tool_version.h
    ${CURL_DIR}/src/tool_vms.c
    ${CURL_DIR}/src/tool_vms.h
    ${CURL_DIR}/src/tool_writeenv.c
    ${CURL_DIR}/src/tool_writeenv.h
    ${CURL_DIR}/src/tool_writeout.c
    ${CURL_DIR}/src/tool_writeout.h
    ${CURL_DIR}/src/tool_xattr.c
    ${CURL_DIR}/src/tool_xattr.h
)

include_directories(${CURL_INCLUDE_DIRECTORIES})

add_library(CURL_LIB ${CURL_LIB_SOURCES})
set_target_properties(CURL_LIB PROPERTIES LINKER_LANGUAGE C)
target_link_libraries(CURL_LIB zlib wsock32 ws2_32)
