include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(GOOGLE_KICK_START_SOURCE_DIRECTORY
    ${GOOGLE_KICK_START_DIR}/src
)

set(GOOGLE_KICK_START_TEST_DIRECTORY
    ${GOOGLE_KICK_START_DIR}/tst
)

set(GOOGLE_KICK_START_INCLUDE_DIRECTORIES
    ${GOOGLE_KICK_START_SOURCE_DIRECTORY}
)

set(GOOGLE_KICK_START_TEST_INCLUDE_DIRECTORIES
    ${GOOGLE_KICK_START_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${GOOGLE_KICK_START_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(GOOGLE_KICK_START_SOURCE_DIRECTORY_LIST ${GOOGLE_KICK_START_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(GOOGLE_KICK_START_SOURCES GOOGLE_KICK_START_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${GOOGLE_KICK_START_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(GOOGLE_KICK_START_TEST_DIRECTORY_LIST ${GOOGLE_KICK_START_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(GOOGLE_KICK_START_TESTS GOOGLE_KICK_START_TEST_DIRECTORY_LIST)

set(GOOGLE_KICK_START_SOURCES_AND_TESTS
    ${GOOGLE_KICK_START_SOURCES}
    ${GOOGLE_KICK_START_TESTS}
)
