set(APRG_CURL_CPP_SOURCE_DIRECTORY
    ${APRG_CURL_CPP_DIR}/src
)

set(APRG_CURL_CPP_TEST_DIRECTORY
    ${APRG_CURL_CPP_DIR}/tst
)

set(APRG_CURL_CPP_INCLUDE_DIRECTORIES
    ${APRG_CURL_CPP_SOURCE_DIRECTORY}
)

set(APRG_CURL_CPP_TEST_INCLUDE_DIRECTORIES
    ${APRG_CURL_CPP_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${APRG_CURL_CPP_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_CURL_CPP_SOURCE_DIRECTORY_LIST ${APRG_CURL_CPP_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_CURL_CPP_SOURCES APRG_CURL_CPP_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${APRG_CURL_CPP_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_CURL_CPP_TEST_DIRECTORY_LIST ${APRG_CURL_CPP_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_CURL_CPP_TESTS APRG_CURL_CPP_TEST_DIRECTORY_LIST)

set(APRG_CURL_CPP_SOURCES_AND_TESTS
    ${APRG_CURL_CPP_SOURCES}
    ${APRG_CURL_CPP_TESTS}
)
