if(WIN32)
    set(APRG_GTEST_DEPENDENCIES gtest ${CMAKE_THREAD_LIBS_INIT})
elseif(APPLE)
    set(APRG_GTEST_DEPENDENCIES gtest ${CMAKE_THREAD_LIBS_INIT})
elseif(UNIX)
    set(APRG_GTEST_DEPENDENCIES gtest ${CMAKE_THREAD_LIBS_INIT} pthread)
endif()

