#Assign Definitions

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug)
endif()

if(CMAKE_BUILD_TYPE MATCHES Debug)
    set(COMMON_DEFINITIONS ${COMMON_DEFINITIONS} -DAPRG_DEBUG)
elseif(CMAKE_BUILD_TYPE MATCHES Release)
    set(COMMON_DEFINITIONS ${COMMON_DEFINITIONS} -DAPRG_RELEASE)
endif()

set(COMMON_DEFINITIONS ${COMMON_DEFINITIONS} -DAPRG_DIR="${APRG_DIR}")

if(WIN32)
    set(COMMON_DEFINITIONS ${COMMON_DEFINITIONS} -DOS_WINDOWS)
elseif(APPLE)
    set(COMMON_DEFINITIONS ${COMMON_DEFINITIONS} -DOS_APPLE)
elseif(UNIX)
    set(COMMON_DEFINITIONS ${COMMON_DEFINITIONS} -DOS_LINUX)
endif()

find_package(Subversion)
if(SUBVERSION_FOUND)
    Subversion_WC_INFO(${PROJECT_SOURCE_DIR} SvnProject IGNORE_SVN_FAILURE)
    message("Code revision is ${SvnProject_WC_REVISION}")
    set(COMMON_DEFINITIONS ${COMMON_DEFINITIONS} -DAPRG_CODE_REVISION="${SvnProject_WC_REVISION}")
endif()

if (TEST_MODE)
    set(COMMON_DEFINITIONS ${COMMON_DEFINITIONS} -DAPRG_TEST_MODE_ON)
else()
    set(COMMON_DEFINITIONS ${COMMON_DEFINITIONS} -DAPRG_TEST_MODE_OFF)
endif()

message("COMMON_DEFINITIONS are: [${COMMON_DEFINITIONS}]")

add_definitions(${COMMON_DEFINITIONS})
