set(RTT_ANALYZER_SOURCE_DIRECTORY
    ${RTT_ANALYZER_DIR}/src
)

set(RTT_ANALYZER_TEST_DIRECTORY
    ${RTT_ANALYZER_DIR}/tst
)

set(RTT_ANALYZER_INCLUDE_DIRECTORIES
    ${RTT_ANALYZER_SOURCE_DIRECTORY}
)

set(RTT_ANALYZER_TEST_INCLUDE_DIRECTORIES
    ${RTT_ANALYZER_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${RTT_ANALYZER_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(RTT_ANALYZER_SOURCE_DIRECTORY_LIST ${RTT_ANALYZER_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(RTT_ANALYZER_SOURCES RTT_ANALYZER_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${RTT_ANALYZER_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(RTT_ANALYZER_TEST_DIRECTORY_LIST ${RTT_ANALYZER_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(RTT_ANALYZER_TESTS RTT_ANALYZER_TEST_DIRECTORY_LIST)

set(RTT_ANALYZER_SOURCES_AND_TESTS
    ${RTT_ANALYZER_SOURCES}
    ${RTT_ANALYZER_TESTS}
)
