set(APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY
    ${APRG_FILE_EXTRACTOR_DIR}/src
)

set(APRG_FILE_EXTRACTOR_TEST_DIRECTORY
    ${APRG_FILE_EXTRACTOR_DIR}/tst
)

set(APRG_FILE_EXTRACTOR_MAIN_DIRECTORY
    ${APRG_FILE_EXTRACTOR_DIR}/main
)

set(APRG_FILE_EXTRACTOR_INCLUDE_DIRECTORIES
    ${APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY}
)

set(APRG_FILE_EXTRACTOR_TEST_INCLUDE_DIRECTORIES
    ${APRG_FILE_EXTRACTOR_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY_LIST ${APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_FILE_EXTRACTOR_SOURCES APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${APRG_FILE_EXTRACTOR_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_FILE_EXTRACTOR_TEST_DIRECTORY_LIST ${APRG_FILE_EXTRACTOR_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_FILE_EXTRACTOR_TESTS APRG_FILE_EXTRACTOR_TEST_DIRECTORY_LIST)

PRINT_STATUS("Looking for MAIN directories in: [${APRG_FILE_EXTRACTOR_MAIN_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_FILE_EXTRACTOR_MAIN_DIRECTORY_LIST ${APRG_FILE_EXTRACTOR_MAIN_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_FILE_EXTRACTOR_MAIN_SOURCES APRG_FILE_EXTRACTOR_MAIN_DIRECTORY_LIST)

set(APRG_FILE_EXTRACTOR_SOURCES_AND_TESTS
    ${APRG_FILE_EXTRACTOR_SOURCES}
    ${APRG_FILE_EXTRACTOR_TESTS}
)
