include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY
    ${QUICKEST_WAY_TO_PROGRAM_DIR}/src
)

set(QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY
    ${QUICKEST_WAY_TO_PROGRAM_DIR}/tst
)

set(QUICKEST_WAY_TO_PROGRAM_INCLUDE_DIRECTORIES
    ${QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY}
)

set(QUICKEST_WAY_TO_PROGRAM_TEST_INCLUDE_DIRECTORIES
    ${QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY_LIST ${QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(QUICKEST_WAY_TO_PROGRAM_SOURCES QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY_LIST ${QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(QUICKEST_WAY_TO_PROGRAM_TESTS QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY_LIST)

set(QUICKEST_WAY_TO_PROGRAM_SOURCES_AND_TESTS
    ${QUICKEST_WAY_TO_PROGRAM_SOURCES}
    ${QUICKEST_WAY_TO_PROGRAM_TESTS}
)
