#define MT_FILE_READER_TEST_DIRECTORY "C:\\APRG\\ACodeReview\\SailIt\\tst\\"
#define MT_FILE_READER_TEST_FILE "C:\\APRG\\ACodeReview\\SailIt\\tst\\Test1.txt"
#define MT_FILE_READER_TEST_INCLUDE_DIRECTORY "C:\\APRG\\ACodeReview\\SailIt\\tst\\include\\"
#define MT_FILE_READER_TEST_INCLUDE_DIRECTORY_NAME "include"
#define MT_FILE_READER_TEST_SUBDIRECTORY "C:\\APRG\\ACodeReview\\SailIt\\tst\\sub_directory\\"
#define MT_FILE_READER_TEST_SUBDIRECTORY_NAME "sub_directory"
