include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(APRG_STATISTICS_SOURCE_DIRECTORY
    ${APRG_STATISTICS_DIR}/src
)

set(APRG_STATISTICS_TEST_DIRECTORY
    ${APRG_STATISTICS_DIR}/tst
)

set(APRG_STATISTICS_INCLUDE_DIRECTORIES
    ${APRG_STATISTICS_SOURCE_DIRECTORY}
)

set(APRG_STATISTICS_TEST_INCLUDE_DIRECTORIES
    ${APRG_STATISTICS_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${APRG_STATISTICS_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_STATISTICS_SOURCE_DIRECTORY_LIST ${APRG_STATISTICS_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_STATISTICS_SOURCES APRG_STATISTICS_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${APRG_STATISTICS_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_STATISTICS_TEST_DIRECTORY_LIST ${APRG_STATISTICS_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_STATISTICS_TESTS APRG_STATISTICS_TEST_DIRECTORY_LIST)

set(APRG_STATISTICS_SOURCES_AND_TESTS
    ${APRG_STATISTICS_SOURCES}
    ${APRG_STATISTICS_TESTS}
)
