include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(HEART_TEE_SOURCE_DIRECTORY
    ${HEART_TEE_DIR}/src
)

set(HEART_TEE_TEST_DIRECTORY
    ${HEART_TEE_DIR}/tst
)

set(HEART_TEE_MAIN_DIRECTORY
    ${HEART_TEE_DIR}/main
)

set(HEART_TEE_INCLUDE_DIRECTORIES
    ${HEART_TEE_SOURCE_DIRECTORY}
)

set(HEART_TEE_TEST_INCLUDE_DIRECTORIES
    ${HEART_TEE_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${HEART_TEE_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(HEART_TEE_SOURCE_DIRECTORY_LIST ${HEART_TEE_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(HEART_TEE_SOURCES HEART_TEE_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${HEART_TEE_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(HEART_TEE_TEST_DIRECTORY_LIST ${HEART_TEE_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(HEART_TEE_TESTS HEART_TEE_TEST_DIRECTORY_LIST)

PRINT_STATUS("Looking for MAIN directories in: [${HEART_TEE_MAIN_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(HEART_TEE_MAIN_DIRECTORY_LIST ${HEART_TEE_MAIN_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(HEART_TEE_MAIN_SOURCES HEART_TEE_MAIN_DIRECTORY_LIST)

set(HEART_TEE_SOURCES_AND_TESTS
    ${HEART_TEE_SOURCES}
    ${HEART_TEE_TESTS}
)
