set(APRG_BITMAP_MANIPULATOR_SOURCE_DIRECTORY
    ${APRG_BITMAP_MANIPULATOR_DIR}/src
)

set(APRG_BITMAP_MANIPULATOR_TEST_DIRECTORY
    ${APRG_BITMAP_MANIPULATOR_DIR}/tst
)

set(APRG_BITMAP_MANIPULATOR_INCLUDE_DIRECTORIES
    ${APRG_BITMAP_MANIPULATOR_SOURCE_DIRECTORY}
)

set(APRG_BITMAP_MANIPULATOR_TEST_INCLUDE_DIRECTORIES
    ${APRG_BITMAP_MANIPULATOR_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${APRG_BITMAP_MANIPULATOR_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_BITMAP_MANIPULATOR_SOURCE_DIRECTORY_LIST ${APRG_BITMAP_MANIPULATOR_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_BITMAP_MANIPULATOR_SOURCES APRG_BITMAP_MANIPULATOR_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${APRG_BITMAP_MANIPULATOR_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_BITMAP_MANIPULATOR_TEST_DIRECTORY_LIST ${APRG_BITMAP_MANIPULATOR_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_BITMAP_MANIPULATOR_TESTS APRG_BITMAP_MANIPULATOR_TEST_DIRECTORY_LIST)

set(APRG_BITMAP_MANIPULATOR_SOURCES_AND_TESTS
    ${APRG_BITMAP_MANIPULATOR_SOURCES}
    ${APRG_BITMAP_MANIPULATOR_TESTS}
)
