include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(SNAPSHOT_DETAILS_SOURCE_DIRECTORY
    ${SNAPSHOT_DETAILS_DIR}/src
)

set(SNAPSHOT_DETAILS_TEST_DIRECTORY
    ${SNAPSHOT_DETAILS_DIR}/tst
)

set(SNAPSHOT_DETAILS_MAIN_DIRECTORY
    ${SNAPSHOT_DETAILS_DIR}/main
)

set(SNAPSHOT_DETAILS_INCLUDE_DIRECTORIES
    ${SNAPSHOT_DETAILS_SOURCE_DIRECTORY}
)

set(SNAPSHOT_DETAILS_TEST_INCLUDE_DIRECTORIES
    ${SNAPSHOT_DETAILS_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${SNAPSHOT_DETAILS_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(SNAPSHOT_DETAILS_SOURCE_DIRECTORY_LIST ${SNAPSHOT_DETAILS_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(SNAPSHOT_DETAILS_SOURCES SNAPSHOT_DETAILS_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${SNAPSHOT_DETAILS_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(SNAPSHOT_DETAILS_TEST_DIRECTORY_LIST ${SNAPSHOT_DETAILS_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(SNAPSHOT_DETAILS_TESTS SNAPSHOT_DETAILS_TEST_DIRECTORY_LIST)

PRINT_STATUS("Looking for MAIN directories in: [${SNAPSHOT_DETAILS_MAIN_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(SNAPSHOT_DETAILS_MAIN_DIRECTORY_LIST ${SNAPSHOT_DETAILS_MAIN_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(SNAPSHOT_DETAILS_MAIN_SOURCES SNAPSHOT_DETAILS_MAIN_DIRECTORY_LIST)

set(SNAPSHOT_DETAILS_SOURCES_AND_TESTS
    ${SNAPSHOT_DETAILS_SOURCES}
    ${SNAPSHOT_DETAILS_TESTS}
)
