include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(DESIGN_PATTERNS_SOURCE_DIRECTORY
    ${DESIGN_PATTERNS_DIR}/src
)

set(DESIGN_PATTERNS_TEST_DIRECTORY
    ${DESIGN_PATTERNS_DIR}/tst
)

set(DESIGN_PATTERNS_INCLUDE_DIRECTORIES
    ${DESIGN_PATTERNS_SOURCE_DIRECTORY}
)

set(DESIGN_PATTERNS_TEST_INCLUDE_DIRECTORIES
    ${DESIGN_PATTERNS_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${DESIGN_PATTERNS_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(DESIGN_PATTERNS_SOURCE_DIRECTORY_LIST ${DESIGN_PATTERNS_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(DESIGN_PATTERNS_SOURCES DESIGN_PATTERNS_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${DESIGN_PATTERNS_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(DESIGN_PATTERNS_TEST_DIRECTORY_LIST ${DESIGN_PATTERNS_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(DESIGN_PATTERNS_TESTS DESIGN_PATTERNS_TEST_DIRECTORY_LIST)

set(DESIGN_PATTERNS_SOURCES_AND_TESTS
    ${DESIGN_PATTERNS_SOURCES}
    ${DESIGN_PATTERNS_TESTS}
)
