set(FEATURE_SOURCE_DIRECTORY
    ${DD_CREATOR_DIR}/src/${FEATURE_FOLDER}/
)

set(FEATURE_TEST_DIRECTORY
    ${DD_CREATOR_DIR}/tst/${FEATURE_FOLDER}/
)

set(FEATURE_INCLUDE_DIRECTORIES
    ${FEATURE_SOURCE_DIRECTORY}
    ${FEATURE_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for ${FEATURE_FOLDER} SRC directories in: [${FEATURE_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(FEATURE_SOURCE_DIRECTORY_LIST ${FEATURE_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(FEATURE_SOURCES FEATURE_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for ${FEATURE_FOLDER} TST directories in: [${FEATURE_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(FEATURE_TEST_DIRECTORY_LIST ${FEATURE_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(FEATURE_TESTS FEATURE_TEST_DIRECTORY_LIST)

set(FEATURE_SOURCES_AND_TESTS
    ${FEATURE_SOURCES}
    ${FEATURE_TESTS}
)

