set(SOOSA_SOURCE_DIRECTORY
    ${SOOSA_DIR}/src
)

set(SOOSA_TEST_DIRECTORY
    ${SOOSA_DIR}/tst
)

set(SOOSA_MAIN_DIRECTORY
    ${SOOSA_DIR}/main
)

set(SOOSA_INCLUDE_DIRECTORIES
    ${SOOSA_SOURCE_DIRECTORY}
)

set(SOOSA_TEST_INCLUDE_DIRECTORIES
    ${SOOSA_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${SOOSA_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(SOOSA_SOURCE_DIRECTORY_LIST ${SOOSA_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(SOOSA_SOURCES SOOSA_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${SOOSA_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(SOOSA_TEST_DIRECTORY_LIST ${SOOSA_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(SOOSA_TESTS SOOSA_TEST_DIRECTORY_LIST)

PRINT_STATUS("Looking for MAIN directories in: [${SOOSA_MAIN_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(SOOSA_MAIN_DIRECTORY_LIST ${SOOSA_MAIN_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(SOOSA_MAIN_SOURCES SOOSA_MAIN_DIRECTORY_LIST)

set(SOOSA_SOURCES_AND_TESTS
    ${SOOSA_SOURCES}
    ${SOOSA_TESTS}
)
