//Sample lists. The list entries could contain multiple arguments.

#define ALBA_XMACROS_SAMPLE_LIST_WITH_ONE_PARAMETER \
    ALBA_XMACROS_SAMPLE_FUNCTION_WITH_ONE_PARAMETER(parameter1InList) \
    ALBA_XMACROS_SAMPLE_FUNCTION_WITH_ONE_PARAMETER(parameter2InList) \
    ALBA_XMACROS_SAMPLE_FUNCTION_WITH_ONE_PARAMETER(parameter3InList)

#define ALBA_XMACROS_SAMPLE_LIST_WITH_TWO_PARAMETERS \
    ALBA_XMACROS_SAMPLE_FUNCTION_WITH_TWO_PARAMETERS(firstParameter1, secondParameter1) \
    ALBA_XMACROS_SAMPLE_FUNCTION_WITH_TWO_PARAMETERS(firstParameter2, secondParameter2) \
    ALBA_XMACROS_SAMPLE_FUNCTION_WITH_TWO_PARAMETERS(firstParameter3, secondParameter3)

