include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(SACK_READER_SOURCE_DIRECTORY
    ${SACK_READER_DIR}/src
)

set(SACK_READER_TEST_DIRECTORY
    ${SACK_READER_DIR}/tst
)

set(SACK_READER_INCLUDE_DIRECTORIES
    ${SACK_READER_SOURCE_DIRECTORY}
)

set(SACK_READER_TEST_INCLUDE_DIRECTORIES
    ${SACK_READER_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${SACK_READER_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(SACK_READER_SOURCE_DIRECTORY_LIST ${SACK_READER_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(SACK_READER_SOURCES SACK_READER_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${SACK_READER_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(SACK_READER_TEST_DIRECTORY_LIST ${SACK_READER_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(SACK_READER_TESTS SACK_READER_TEST_DIRECTORY_LIST)

set(SACK_READER_SOURCES_AND_TESTS
    ${SACK_READER_SOURCES}
    ${SACK_READER_TESTS}
)
