include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(APRG_GNU_PLOT_SOURCE_DIRECTORY
    ${APRG_GNU_PLOT_DIR}/src
)

set(APRG_GNU_PLOT_TEST_DIRECTORY
    ${APRG_GNU_PLOT_DIR}/tst
)

set(APRG_GNU_PLOT_INCLUDE_DIRECTORIES
    ${APRG_GNU_PLOT_SOURCE_DIRECTORY}
)

set(APRG_GNU_PLOT_TEST_INCLUDE_DIRECTORIES
    ${APRG_GNU_PLOT_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${APRG_GNU_PLOT_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_GNU_PLOT_SOURCE_DIRECTORY_LIST ${APRG_GNU_PLOT_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_GNU_PLOT_SOURCES APRG_GNU_PLOT_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${APRG_GNU_PLOT_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_GNU_PLOT_TEST_DIRECTORY_LIST ${APRG_GNU_PLOT_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_GNU_PLOT_TESTS APRG_GNU_PLOT_TEST_DIRECTORY_LIST)

set(APRG_GNU_PLOT_SOURCES_AND_TESTS
    ${APRG_GNU_PLOT_SOURCES}
    ${APRG_GNU_PLOT_TESTS}
)
