# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  buildAprgWebsite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.2'

      - name: Change directory to aprg website
        run: cd docs/ReactProjects/aprgWebsite && pwd
        
      - name: Installing my packages
        run: pwd && npm ci

      - name: Build my App
        run: npm run build && npm run export && touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: actions/deploy-pages@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: public # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
