# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [main]
    paths:
      - '.github/**'
      - 'docs/ReactProjects/aprgWebsite/**'

jobs:
  buildAprgWebsite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.2'
        
      - name: Installing my packages
        run: cd docs/ReactProjects/aprgWebsite && npm ci

      - name: Build my App
        run: cd docs/ReactProjects/aprgWebsite npm run build && npm run export && touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: actions/deploy-pages@v2
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: docs/ReactProjects/aprgWebsite/out # The folder the action should deploy.
